% 使用4个下标确定一个矩阵的内容 [x0 -> x1][y0 -> y1]
function C = C_SquareMatrixMultiplyRecursive(A, B, a11, a12, a21, a22, b11, b12, b21, b22)
    n = a12 - a11 + 1;
    C = zeros(n);
    if n == 1
        C(n,n) = A(a22,a11)*B(b22,b11)
    else
        C(a11:a12/2, a21:a22/2)                =  C_SquareMatrixMultiplyRecursive(A, B, a11,               a12/2,          a21,               a22/2,                  ...
                                                                                        b11,               b12/2,          b21,               b22/2 )               + ...
                                                  C_SquareMatrixMultiplyRecursive(A, B, ceil((a11+a12)/2) ,a12,            a21,               a22/2,                  ...
                                                                                        b11,               floor(b12/2),   ceil((b21+b22)/2), b22)
        C(a11:a12/2, ceil((a11+a12)/2):a22)    =  C_SquareMatrixMultiplyRecursive(A, B, a11,               a12/2,          a21,               a22/2,                  ...
                                                                                        ceil((b11+b12)/2) ,b12,            b21,               b22/2 )               + ...
                                                  C_SquareMatrixMultiplyRecursive(A, B, ceil((a11+a12)/2) ,a12,            a21,               a22/2,                  ...
                                                                                        ceil((b11+b12)/2), b12,            ceil((b21+b22)/2), b22)
       C(ceil((a11+a12)/2):a12, a21:a22/2)     =  C_SquareMatrixMultiplyRecursive(A, B, a11,               floor(a12/2),   ceil((a21+a22)/2), a22,                    ...
                                                                                        b11,               b12/2,          b21,               b22/2 )               + ...
                                                  C_SquareMatrixMultiplyRecursive(A, B, ceil((a11+a12)/2) ,a12,            ceil((a22+a21)/2), a22,                    ...
                                                                                        b11,               floor(b12/2),   ceil((b21+b22)/2), b22)
       C(ceil((a11+a12)/2):a12, ceil(a21+a22/2):a22) =  C_SquareMatrixMultiplyRecursive(A, B, a11,               floor(a12/2),   ceil((a21+a22)/2), a22,                   ...
                                                                                        ceil((b11+b12)/2) ,b12,            b21,               b22/2 )               + ...
                                                  C_SquareMatrixMultiplyRecursive(A, B, ceil((a11+a12)/2) ,a12,            ceil((a22+a21)/2), a22,                     ...
                                                                                        ceil((b11+b12)/2), b12,            ceil((b21+b22)/2), b22)
    end
end